# Site settings
title: 小智晖的AI单词库
SEOTitle: 小智晖的AI单词库 | vocabulary-book-by-deepseek
header-img: imgs/home-bg-o.jpg
email: whutluohui@gmail.com
description: "这里是 小智晖 的个人博客，与你一起发现更大的世界 | 要做一个有 swag 的程序员"
keyword: "小智晖, vxiaozhi, VXiaoZhi, 小智晖的AI单词库, vocabulary-book-by-deepseek, 博客, 个人网站, 互联网, Web, JavaScript, React, React Native, 后端, 高并发, 高性能"
url: "https://word.vxiaozhi.com" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: wmxiaozhi
zhihu_username: vxiaozhi
github_username: vxiaozhi
twitter_username: wmxiaozhi
#facebook_username:  vxiaozhi
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
    "SUMMARY.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate,jekyll-sitemap,]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: vxiaozhi

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: "UA-xxxx" # Format: UA-xxxxxx-xx
# ga_domain: vxiaozhi.com

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "要做一个有 swag 的程序员 <br> React Team @ Meta"
sidebar-avatar: https://github.com/vxiaozhi.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "vxiaozhi", href: "https://www.vxiaozhi.com" },
    { title: "ruanyf/weekly", href: "https://github.com/ruanyf/weekly" },
  ]

